services:
  db:
    image: mysql:8.4
    container_name: siimut-db-mysql
    env_file:
      - .env.docker
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-${DB_DATABASE:-laravel}}
      MYSQL_USER: ${MYSQL_USER:-${DB_USERNAME:-laravel}}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-${DB_PASSWORD:-laravel}}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # host:container
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
